global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "numberlink-backend"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "numberlink-postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "numberlink/numberlink"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:9464"]
