{
 "title": "BU-MTVLAB SpringBoot Observability",
 "description": "To setup observability for spring boot apps - https://brainupgrade.in",
 "tags": [
  "brainupgrade.in",
  "spring boot",
  "Java Spring Apps",
  "Prometheus",
  "Loki",
  "Tempo"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(http_server_requests_seconds_count, application)"
   },
   {
    "name": "app_name",
    "label": "Application",
    "query": "label_values(http_server_requests_seconds_count, application)"
   },
   { "name": "log_keyword", "label": "Log Query" },
   {
    "name": "service_namespace",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"${service_namespace}.*\"},job)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"${service_namespace}/${service_name}\"},job)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"}[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(uri) (increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"}[$__range])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=~\"${app_name}\"}) / sum by(uri)(http_server_requests_seconds_count{application=~\"${app_name}\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", status=~\"4.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"})) or on() vector(0)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"})) or on() vector(0)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=~\"${app_name}\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=~\"${app_name}\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(type) (rate({app=~\"${app}.*\"} | pattern `<date> <time> <_>=<trace_id> <_>=<span_id> <_>=<trace_flags> <type> <_> --- <msg>` | type != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .service_instance_id}}{{if .thread_name}}/{{alignRight 20 .thread_name}}{{else if eq \"java\" .telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .scope_name }}{{alignRight 40 .scope_name}}{{end}}\u001b[0m {{__line__}} {{if .trace_id}} \u001b[37m\u001b[3m[{{.trace_id}}]{{end}}`",
     "maxLines": 80
    }
   ]
  },
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Service Mesh",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Website", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Logins succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__range])) or vector(0))\n  +\n  (\n    (\n      sum(\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__range])\n        unless\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__range] offset $__range)\n      )\n      and on()\n      ((sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__range])) or vector(0)) == 0)\n    ) or vector(0)\n  )\n)",
     "legendFormat": "succeeded"
    }
   ]
  },
  {
   "title": "Signups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/register\", status=~\"2.*\"}[$__range])) or vector(0))\n  +\n  (\n    (\n      sum(\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/register\", status=~\"2.*\"}[$__range])\n        unless\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/register\", status=~\"2.*\"}[$__range] offset $__range)\n      )\n      and on()\n      ((sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/register\", status=~\"2.*\"}[$__range])) or vector(0)) == 0)\n    ) or vector(0)\n  )\n)",
     "legendFormat": "Signups"
    }
   ]
  },
  {
   "title": "Signouts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/logout\", status=\"204\"}[$__range])) or vector(0))\n  +\n  (\n    (\n      sum(\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/logout\", status=\"204\"}[$__range])\n        unless\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/logout\", status=\"204\"}[$__range] offset $__range)\n      )\n      and on()\n      ((sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/logout\", status=\"204\"}[$__range])) or vector(0)) == 0)\n    ) or vector(0)\n  )\n)",
     "legendFormat": "Signouts"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"${app_name}\", area=\"heap\"})",
     "legendFormat": "memory"
    },
    {
     "expr": "process_cpu_usage{application=~\"${app_name}\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "system_cpu_usage{application=~\"${app_name}\"}",
     "legendFormat": "system cpu"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "succeeded"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status!~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status=~\"2.*\"}[$__rate_interval] offset 1h))",
     "legendFormat": "succeeded (-1 hour)"
    }
   ]
  },
  {
   "title": "Logins failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status!~\"2.*\"}[$__range])) or vector(0))\n  +\n  (\n    (\n      sum(\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status!~\"2.*\"}[$__range])\n        unless\n        last_over_time(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status!~\"2.*\"}[$__range] offset $__range)\n      )\n      and on()\n      ((sum(increase(http_server_requests_seconds_count{application=~\"${app_name}\", uri=\"/api/login\", status!~\"2.*\"}[$__range])) or vector(0)) == 0)\n    ) or vector(0)\n  )\n)",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "HTTP access log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Access log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx\"}",
     "maxLines": 200
    }
   ]
  }
 ]
}